#pragma once

#include "sdkconfig.h"

// Config file fallback values
#ifdef CONFIG_CONFIG_FILE_PATH
#define CONFIG_FILE_PATH CONFIG_CONFIG_FILE_PATH
#endif

#ifdef CONFIG_FALLBACK_WIFI_SSID
#define FALLBACK_WIFI_SSID CONFIG_FALLBACK_WIFI_SSID
#endif

#ifdef CONFIG_FALLBACK_WIFI_PWD
#define FALLBACK_WIFI_PWD CONFIG_FALLBACK_WIFI_PWD
#endif

#ifdef CONFIG_FALLBACK_DEVICE_NAME
#define FALLBACK_DEVICE_NAME CONFIG_FALLBACK_DEVICE_NAME
#endif

#ifndef CONFIG_FILE_PATH
#define CONFIG_FILE_PATH "config.txt"
#endif
#ifndef FALLBACK_WIFI_SSID
#define FALLBACK_WIFI_SSID "SSID"
#endif
#ifndef FALLBACK_WIFI_PWD
#define FALLBACK_WIFI_PWD "PASSWORD"
#endif
#ifndef FALLBACK_DEVICE_NAME
#define FALLBACK_DEVICE_NAME "SPYCAM"
#endif

// LED Options:
#ifdef CONFIG_FLASH_LED_PIN
#define FLASH_LED_PIN CONFIG_FLASH_LED_PIN
#endif

#ifndef FLASH_LED_PIN
#define FLASH_LED_PIN 4
#endif

// OTA Options:
#ifdef CONFIG_OTA_FEATURE
#define OTA_FEATURE
#endif

#ifdef OTA_FEATURE
#ifdef CONFIG_FALLBACK_FIRMWARE_UPGRADE_URL
#define FALLBACK_FIRMWARE_UPGRADE_URL CONFIG_FALLBACK_FIRMWARE_UPGRADE_URL
#endif

#ifdef CONFIG_OTA_RECV_TIMEOUT
#define OTA_RECV_TIMEOUT CONFIG_OTA_RECV_TIMEOUT
#endif

#ifdef CONFIG_SKIP_COMMON_NAME_CHECK
#define SKIP_COMMON_NAME_CHECK
#endif

#ifndef FALLBACK_FIRMWARE_UPGRADE_URL
#define FALLBACK_FIRMWARE_UPGRADE_URL "https://192.168.42.42:42424/upgrade.bin"
#endif

#ifndef OTA_RECV_TIMEOUT
#define OTA_RECV_TIMEOUT 5000
#endif
#endif

// Time Lapse Options
#ifdef CONFIG_CAM_TASK_TIMER_GROUP_NUM
#define CAM_TASK_TIMER_GROUP_NUM CONFIG_CAM_TASK_TIMER_GROUP_NUM
#endif
#ifdef CONFIG_CAM_TASK_TIMER_NUM
#define CAM_TASK_TIMER_NUM CONFIG_CAM_TASK_TIMER_NUM
#endif
#ifdef CONFIG_TMP_INDEX_FILE_PATH
#define TMP_INDEX_FILE_PATH CONFIG_TMP_INDEX_FILE_PATH
#endif

#ifndef CAM_TASK_TIMER_GROUP_NUM
#define CAM_TASK_TIMER_GROUP_NUM 1
#endif
#ifndef CAM_TASK_TIMER_NUM
#define CAM_TASK_TIMER_NUM 1
#endif
#ifndef TMP_INDEX_FILE_PATH
#define TMP_INDEX_FILE_PATH ".tmpavi.idx"
#endif