#pragma once

#include "sdkconfig.h"

// Config file fallback values
#ifdef CONFIG_CONFIG_FILE_PATH
#define CONFIG_FILE_PATH CONFIG_CONFIG_FILE_PATH
#endif

#ifdef CONFIG_FALLBACK_WIFI_SSID
#define FALLBACK_WIFI_SSID CONFIG_FALLBACK_WIFI_SSID
#endif

#ifdef CONFIG_FALLBACK_WIFI_PWD
#define FALLBACK_WIFI_PWD CONFIG_FALLBACK_WIFI_PWD
#endif

#ifdef CONFIG_WIFI_MAXIMUM_RETRY
#define WIFI_MAXIMUM_RETRY CONFIG_WIFI_MAXIMUM_RETRY
#endif

#ifdef CONFIG_FALLBACK_AP_SSID
#define FALLBACK_AP_SSID CONFIG_FALLBACK_AP_SSID
#endif

#ifdef CONFIG_FALLBACK_AP_PWD
#define FALLBACK_AP_PWD CONFIG_FALLBACK_AP_PWD
#endif

#ifdef CONFIG_FALLBACK_AP_IP_ADDR
#define FALLBACK_AP_IP_ADDR CONFIG_FALLBACK_AP_IP_ADDR
#endif

#ifdef CONFIG_FALLBACK_DEVICE_NAME
#define FALLBACK_DEVICE_NAME CONFIG_FALLBACK_DEVICE_NAME
#endif

#ifndef CONFIG_FILE_PATH
#define CONFIG_FILE_PATH "config.txt"
#endif
#ifndef FALLBACK_WIFI_SSID
#define FALLBACK_WIFI_SSID ""
#endif
#ifndef FALLBACK_WIFI_PWD
#define FALLBACK_WIFI_PWD ""
#endif
#ifndef WIFI_MAXIMUM_RETRY
#define WIFI_MAXIMUM_RETRY 5
#endif
#ifndef FALLBACK_AP_SSID
#define FALLBACK_AP_SSID ""
#endif
#ifndef FALLBACK_AP_PWD
#define FALLBACK_AP_PWD ""
#endif
#ifndef FALLBACK_AP_IP_ADDR
#define FALLBACK_AP_IP_ADDR ""
#endif
#ifndef FALLBACK_DEVICE_NAME
#define FALLBACK_DEVICE_NAME "SPYCAM"
#endif

// Flash LED Options: //TODO update/add

// TODO changable?
#define FLASH_LIGHT_WAIT 150 / portTICK_PERIOD_MS

#ifdef CONFIG_LED_LEDC_LOW_SPEED_MODE
#define CONFIG_LED_LEDC_SPEED_MODE LEDC_LOW_SPEED_MODE
#else
#define CONFIG_LED_LEDC_SPEED_MODE LEDC_HIGH_SPEED_MODE
#endif

// OTA Options:
#ifdef CONFIG_OTA_FEATURE
#define OTA_FEATURE
#endif

#ifdef OTA_FEATURE
#ifdef CONFIG_FALLBACK_FIRMWARE_UPGRADE_URL
#define FALLBACK_FIRMWARE_UPGRADE_URL CONFIG_FALLBACK_FIRMWARE_UPGRADE_URL
#endif

#ifdef CONFIG_OTA_RECV_TIMEOUT
#define OTA_RECV_TIMEOUT CONFIG_OTA_RECV_TIMEOUT
#endif

#ifdef CONFIG_SKIP_COMMON_NAME_CHECK
#define SKIP_COMMON_NAME_CHECK
#endif

#ifndef FALLBACK_FIRMWARE_UPGRADE_URL
#define FALLBACK_FIRMWARE_UPGRADE_URL "https://192.168.42.42:42424/upgrade.bin"
#endif

#ifndef OTA_RECV_TIMEOUT
#define OTA_RECV_TIMEOUT 5000
#endif
#endif

// Time Lapse Options
#ifdef CONFIG_CAM_TASK_TIMER_GROUP_NUM
#define CAM_TASK_TIMER_GROUP_NUM CONFIG_CAM_TASK_TIMER_GROUP_NUM
#endif
#ifdef CONFIG_CAM_TASK_TIMER_NUM
#define CAM_TASK_TIMER_NUM CONFIG_CAM_TASK_TIMER_NUM
#endif
#ifdef CONFIG_TMP_INDEX_FILE_PATH
#define TMP_INDEX_FILE_PATH CONFIG_TMP_INDEX_FILE_PATH
#endif

#ifndef CAM_TASK_TIMER_GROUP_NUM
#define CAM_TASK_TIMER_GROUP_NUM 1
#endif
#ifndef CAM_TASK_TIMER_NUM
#define CAM_TASK_TIMER_NUM 1
#endif
#ifndef TMP_INDEX_FILE_PATH
#define TMP_INDEX_FILE_PATH ".tmpavi.idx"
#endif
// TODO changable?
#ifndef TIMER_DIVIDER
#define TIMER_DIVIDER 65536 //Range is 2 to 65536
#endif
// TODO changable?
#define JPG_QUALITY 80

// ESP Camera boards

#if CONFIG_CAMERA_MODEL_WROVER_KIT
#define CAM_BOARD "WROVER-KIT"
#define PWDN_GPIO_NUM -1
#define RESET_GPIO_NUM -1
#define XCLK_GPIO_NUM 21
#define SIOD_GPIO_NUM 26
#define SIOC_GPIO_NUM 27

#define Y9_GPIO_NUM 35
#define Y8_GPIO_NUM 34
#define Y7_GPIO_NUM 39
#define Y6_GPIO_NUM 36
#define Y5_GPIO_NUM 19
#define Y4_GPIO_NUM 18
#define Y3_GPIO_NUM 5
#define Y2_GPIO_NUM 4
#define VSYNC_GPIO_NUM 25
#define HREF_GPIO_NUM 23
#define PCLK_GPIO_NUM 22

#elif CONFIG_CAMERA_MODEL_ESP32_CAM_BOARD
#define CAM_BOARD "ESP-DEVCAM"
#define PWDN_GPIO_NUM 32
#define RESET_GPIO_NUM 33
#define XCLK_GPIO_NUM 4
#define SIOD_GPIO_NUM 18
#define SIOC_GPIO_NUM 23

#define Y9_GPIO_NUM 36
#define Y8_GPIO_NUM 19
#define Y7_GPIO_NUM 21
#define Y6_GPIO_NUM 39
#define Y5_GPIO_NUM 35
#define Y4_GPIO_NUM 14
#define Y3_GPIO_NUM 13
#define Y2_GPIO_NUM 34
#define VSYNC_GPIO_NUM 5
#define HREF_GPIO_NUM 27
#define PCLK_GPIO_NUM 25

#elif CONFIG_CAMERA_MODEL_ESP_EYE
#define CAM_BOARD "ESP-EYE"
#define PWDN_GPIO_NUM -1
#define RESET_GPIO_NUM -1
#define XCLK_GPIO_NUM 4
#define SIOD_GPIO_NUM 18
#define SIOC_GPIO_NUM 23

#define Y9_GPIO_NUM 36
#define Y8_GPIO_NUM 37
#define Y7_GPIO_NUM 38
#define Y6_GPIO_NUM 39
#define Y5_GPIO_NUM 35
#define Y4_GPIO_NUM 14
#define Y3_GPIO_NUM 13
#define Y2_GPIO_NUM 34
#define VSYNC_GPIO_NUM 5
#define HREF_GPIO_NUM 27
#define PCLK_GPIO_NUM 25

#elif CONFIG_CAMERA_MODEL_M5STACK_PSRAM
#define CAM_BOARD "M5CAM"
#define PWDN_GPIO_NUM -1
#define RESET_GPIO_NUM 15
#define XCLK_GPIO_NUM 27
#define SIOD_GPIO_NUM 25
#define SIOC_GPIO_NUM 23

#define Y9_GPIO_NUM 19
#define Y8_GPIO_NUM 36
#define Y7_GPIO_NUM 18
#define Y6_GPIO_NUM 39
#define Y5_GPIO_NUM 5
#define Y4_GPIO_NUM 34
#define Y3_GPIO_NUM 35
#define Y2_GPIO_NUM 32
#define VSYNC_GPIO_NUM 22
#define HREF_GPIO_NUM 26
#define PCLK_GPIO_NUM 21

#elif CONFIG_CAMERA_MODEL_M5STACK_WIDE
#define CAM_BOARD "M5CAMW"
#define PWDN_GPIO_NUM -1
#define RESET_GPIO_NUM 15
#define XCLK_GPIO_NUM 27
#define SIOD_GPIO_NUM 22
#define SIOC_GPIO_NUM 23

#define Y9_GPIO_NUM 19
#define Y8_GPIO_NUM 36
#define Y7_GPIO_NUM 18
#define Y6_GPIO_NUM 39
#define Y5_GPIO_NUM 5
#define Y4_GPIO_NUM 34
#define Y3_GPIO_NUM 35
#define Y2_GPIO_NUM 32
#define VSYNC_GPIO_NUM 25
#define HREF_GPIO_NUM 26
#define PCLK_GPIO_NUM 21

#elif CONFIG_CAMERA_MODEL_AI_THINKER
#define CAM_BOARD "AI-THINKER"
#define PWDN_GPIO_NUM 32
#define RESET_GPIO_NUM -1
#define XCLK_GPIO_NUM 0
#define SIOD_GPIO_NUM 26
#define SIOC_GPIO_NUM 27

#define Y9_GPIO_NUM 35
#define Y8_GPIO_NUM 34
#define Y7_GPIO_NUM 39
#define Y6_GPIO_NUM 36
#define Y5_GPIO_NUM 21
#define Y4_GPIO_NUM 19
#define Y3_GPIO_NUM 18
#define Y2_GPIO_NUM 5
#define VSYNC_GPIO_NUM 25
#define HREF_GPIO_NUM 23
#define PCLK_GPIO_NUM 22

#elif CONFIG_CAMERA_MODEL_CUSTOM
#define CAM_BOARD "CUSTOM"
#define PWDN_GPIO_NUM CONFIG_CAMERA_PIN_PWDN
#define RESET_GPIO_NUM CONFIG_CAMERA_PIN_RESET
#define XCLK_GPIO_NUM CONFIG_CAMERA_PIN_XCLK
#define SIOD_GPIO_NUM CONFIG_CAMERA_PIN_SIOD
#define SIOC_GPIO_NUM CONFIG_CAMERA_PIN_SIOC

#define Y9_GPIO_NUM CONFIG_CAMERA_PIN_Y9
#define Y8_GPIO_NUM CONFIG_CAMERA_PIN_Y8
#define Y7_GPIO_NUM CONFIG_CAMERA_PIN_Y7
#define Y6_GPIO_NUM CONFIG_CAMERA_PIN_Y6
#define Y5_GPIO_NUM CONFIG_CAMERA_PIN_Y5
#define Y4_GPIO_NUM CONFIG_CAMERA_PIN_Y4
#define Y3_GPIO_NUM CONFIG_CAMERA_PIN_Y3
#define Y2_GPIO_NUM CONFIG_CAMERA_PIN_Y2
#define VSYNC_GPIO_NUM CONFIG_CAMERA_PIN_VSYNC
#define HREF_GPIO_NUM CONFIG_CAMERA_PIN_HREF
#define PCLK_GPIO_NUM CONFIG_CAMERA_PIN_PCLK
#endif